Algoritmo "ExemploDesvioCondicional"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : obama
// Descrição   : Converte a temperatura de celsius para fahrenheit
// Autor(a)    : isabella
// Data atual  : 25/08/2021
Var
valor:inteiro



Inicio

Escreval("Desvio Condicional Simples")
Escreval("Digite um valor")
Leia (valor)
se (valor<10) entao
Escreva ("O valor é menor que 10")
fimse

Fimalgoritmo
