Algoritmo "Exercicio32"
// Disciplina   : [Javascript e Lógica de Programação]
// Professor   : Jailson
// Descrição   :  Ler o nome de 2 times e o número de gols marcados na partida (para cada time). Escrever o nome do vencedor. Caso não haja vencedor deverá ser impressa a palavra EMPATE.
// Autor(a)    : isabella
// Data atual  : 27/08/2021
Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo