Algoritmo "Exibir mensagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem
// Autor(a)    : Isabella Alves
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval ("Professor Obama")
Escreval ("Equipe 04")
Escreval ("Isabella")

Fimalgoritmo