Algoritmo "LacoRepeticaoEnquanto"
// Disciplina   : [JS e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Laço Enquanto
// Autor(a)    : Isabella
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora<10 faca
Escreval("Obama é 10")
contadora <-contadora+1
fimenquanto


Fimalgoritmo